Feature/cmp 127 s3 bucket versions followup
CloudBoltSoftware/applet-s3-bucket-browser pull request #6
Opened 2023-12-04 21:50 UTC by tropotorres

Ticket - [CMP-127](https://cloudbolt.atlassian.net/browse/CMP-127)
Engineer @tropotorres 

Recommend waiting until after  [cb-applet: feat(): [CMP-961] Updated cbapplet template OPEN](https://github.com/CloudBoltSoftware/cb-applet/pull/27) is merged 
And Post CUI -> SSP conversion

Also ran prettier and lint on repo

Tasks Completed
- [ ] Switch the BE to use IWHs instead of a XUI (this will be a big improvement as it will obviate the need for the admin to import the XUI and for the user to navigate to /dashboard/ first)
- [ ] Verify all functionality again
- [ ] Comment back in versioning toggle and table
- [ ] Adjust Version tab (and button)
- [ ] Confirm enough information is on Overview Tab
- [ ] Confirm Restore Button functionality

Tasks skipped (optional added functionality)
- Check if Multifile Upload can be done with the folder upload
- Add state management(?) to handle repetitively passed information

2023-12-06 19:31 UTC, orvisevans requested changes
The actual code changes look good to me! However, I do have a question regarding the Inbound Web Hooks.

They're required to get this to work, but we don't have any kind of compile-from-source pipeline step for them. Where are the required IWH's now?

If the answer is nowhere, I'm definitely open to options. But here's my suggestion:
 - Add the IWH `.zip` files to this repo's `xui/src` folder (or to whatever sub-directory they have to be in there for the built applet import to work).
   - FYI: the `js-xui-bundler` tool uses this folder for supplementary files to be bundled into the built applet `.zip` file.
 - Add metadata to `package.json` to point to the bundled IWH (again, for the `js-xui-bundler` tool to use), like:
```json
"met_inbound_web_hook_dependencies": [
        "inbound_web_hook_defaultauth.zip"
    ],
```
My goal with this suggestion is to:
 - Get the IWH dependencies into source control somewhere
 - Give this repo everything it needs so that a simple `npm run build` will build a working applet with its dependencies

2023-12-06 19:31 UTC, orvisevans commented on README.md
> +CB Applets extend the CloudBolt UI using Vue.js with Vuetify component library. These work extensively through the Self-Service Portal (SSP) and in certain places on the Cloudbolt HUI. Applets can ta
Rather than attempting to keep this up to date for general Applet info, you're welcome to delete all that (keeping just what's relevant to this specific repo), and add a link to the cb-applet readme. Either works, but that might be easier/more accurate in the long run

2023-12-08 16:57 UTC, tropotorres commented
> The actual code changes look good to me! However, I do have a question regarding the Inbound Web Hooks.
> 
> They're required to get this to work, but we don't have any kind of compile-from-source pipeline step for them. Where are the required IWH's now?
> 
> If the answer is nowhere, I'm definitely open to options. But here's my suggestion:
> 
> * Add the IWH `.zip` files to this repo's `xui/src` folder (or to whatever sub-directory they have to be in there for the built applet import to work).
>   
>   * FYI: the `js-xui-bundler` tool uses this folder for supplementary files to be bundled into the built applet `.zip` file.
> * Add metadata to `package.json` to point to the bundled IWH (again, for the `js-xui-bundler` tool to use), like:
> 
> ```json
> "met_inbound_web_hook_dependencies": [
>         "inbound_web_hook_defaultauth.zip"
>     ],
> ```
> 
> My goal with this suggestion is to:
> 
> * Get the IWH dependencies into source control somewhere
> * Give this repo everything it needs so that a simple `npm run build` will build a working applet with its dependencies

Talked to Orvis about this, since there still needs to be a little work before the IWH is bundled at this level (regarding the xui exporter), going to continue with this PR as is and create a followup

2023-12-08 17:25 UTC, tropotorres commented on README.md
> +CB Applets extend the CloudBolt UI using Vue.js with Vuetify component library. These work extensively through the Self-Service Portal (SSP) and in certain places on the Cloudbolt HUI. Applets can ta
There's nothing that's super specific to this repo. I do have another [PR for updating the main applet repo](https://github.com/CloudBoltSoftware/cb-applet/pull/27) with info about HUI targets though

2023-12-11 19:37 UTC, orvisevans approved these changes

2023-12-11 19:37 UTC, merged